name: "Deploy (trigger)"

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.label.name == 'preview'
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/reusable-deploy-prenv.yml
    with:
      pr: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      images: |
        [
          {"name": "backend", "context": "backend", "dockerfile": "docker/backend/Dockerfile", "cache": true},
          {"name": "db", "context": "db", "dockerfile": "docker/db/Dockerfile", "cache": false},
          {"name": "frontend", "context": "frontend", "dockerfile": "docker/frontend/Dockerfile", "cache": true}
        ]
